SELECT 
    EXTRACT(MONTH FROM DT_TRANSACAO) AS mes,
    EXTRACT(YEAR FROM DT_TRANSACAO) AS ano,
    SUM(CASE WHEN CD_TRANSACAO = '110' THEN VR_TRANSACAO ELSE 0 END) AS total_cash_in,
    SUM(CASE WHEN CD_TRANSACAO = '220' THEN VR_TRANSACAO ELSE 0 END) AS total_cash_out,
    CASE 
        WHEN SUM(CASE WHEN CD_TRANSACAO = '220' THEN VR_TRANSACAO ELSE 0 END) = 0 THEN NULL
        ELSE SUM(CASE WHEN CD_TRANSACAO = '110' THEN VR_TRANSACAO ELSE 0 END) 
             / SUM(CASE WHEN CD_TRANSACAO = '220' THEN VR_TRANSACAO ELSE 0 END)
    END AS proporcao_cash_in_out
FROM 
    TbTransacoes
GROUP BY 
    EXTRACT(MONTH FROM DT_TRANSACAO),
    EXTRACT(YEAR FROM DT_TRANSACAO)
ORDER BY 
    ano DESC, mes DESC;
